//
// Generated by afu_json_mgr from ../../hw/afu.json
//

`ifndef __AFU_JSON_INFO__
`define __AFU_JSON_INFO__

`define AFU_ACCEL_NAME "afu"
`define AFU_ACCEL_UUID 128'h4a486599_0504_4427_8806_3bd96fdf0ce7
`define AFU_IMAGE_POWER 0
`define AFU_TOP_IFC "ccip_std_afu"

`endif // __AFU_JSON_INFO__
